version: "3.7"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "${NGINX_PORT_HTTP}:${NGINX_PORT_HTTP}"
    networks:
      - brain_challenge
    volumes:
      - ./:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    container_name: ${APP_NAME}_nginx_${APP_ENV}
    environment:
      - FASTCGI_PASS=${APP_NAME}_php_${APP_ENV}:9000
      - NGINX_PORT_HTTP=${NGINX_PORT_HTTP}
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: php/${APP_ENV:-local}/Dockerfile
    networks:
      - brain_challenge
    volumes:
      - ./:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    container_name: ${APP_NAME}_php_${APP_ENV}
  mysql:
    networks:
      - brain_challenge
    image: 'mysql:latest'
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-brain_challenge}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    container_name: ${APP_NAME}_mysql_${APP_ENV}
  redis:
    image: redis:latest
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - brain_challenge
    container_name: ${APP_NAME}_redis_${APP_ENV}
networks:
  brain_challenge:
    driver: bridge
