name: Deploy to production

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest Code
      uses: actions/checkout@v3

    - name: Sync Files
      run: |
        apt-get update && apt-get install -y git-ftp
        git reset --hard
        git config git-ftp.syncroot ${{ secrets.SFTP_DESTINATION_FOLDER }}
        git ftp init -u ${{ secrets.USER }} -p ${{ secrets.TARGET_DIR }} ${{ secrets.HOST }} || git ftp push -u ${{ secrets.USER }} -p ${{ secrets.TARGET_DIR }} ${{ secrets.HOST }}
